# Generated by Django 5.0.3 on 2024-04-11 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_cert_donor_alter_cert_title_alter_exp_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
