# Generated by Django 5.0.3 on 2024-04-11 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_project_code_url_alter_project_preview_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert',
            name='granted_on',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='exp',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exp',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='exp',
            name='start_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='projects/'),
        ),
    ]
