# Generated by Django 5.0.3 on 2024-04-08 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='cert',
            name='details_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='cert',
            name='donor',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/'),
        ),
        migrations.AddField(
            model_name='user',
            name='resume',
            field=models.FileField(blank=True, upload_to='resumes'),
        ),
        migrations.CreateModel(
            name='SKILL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(blank=True, max_length=25)),
                ('image', models.ImageField(blank=True, upload_to='skills/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skils', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
