# Generated by Django 5.0.3 on 2024-04-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_skill_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert',
            name='donor',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='cert',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exp',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.FileField(blank=True, upload_to='resumes/'),
        ),
    ]
