# Generated by Django 5.0.3 on 2024-04-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_skill_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='preview_url',
            field=models.URLField(null=True),
        ),
    ]
