# Generated by Django 5.0.3 on 2024-04-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_project_code_url_alter_project_preview_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='preview_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
